require "user.autopairs"
require "user.colorscheme"
require "user.cmp"
require "user.keymaps"
-- require "user.lsp"
require "user.mason" -- TODO: Restructure what we're doing here
require "user.null-ls"
require "user.nvim-tree"
require "user.options"
require "user.plugins"
require "user.telescope"
require "user.treesitter"
require "user.gitsigns"
require "user.telekasten"
require "user.whichkey"
